### ISSUE TITLE
Market Maker ID in Book

### ISSUE THREAD

**Issue by sirinath** [jvirtanen/parity#52]
Can you add market maker to the book.

**Comment by jvirtanen** [comment]
Can you elaborate on your use case?

**Comment by sirinath** [comment]
L2 quotes have MM details.

**Comment by sirinath** [comment]
Wondering what your thoughts are on this.

**Comment by jvirtanen** [comment]
Currently both the order book reconstruction and the matching engine maintain the minimum amount of information needed for the task at hand, and the trading system, for example, maintains auxliary storage for additional information per order.

I would not add the market maker identifier directly to the information maintained by the reconstruction and matching libraries, because it is not needed for those. Instead, I would perhaps rephrase the question as follows:

> Should there be a way to associate auxliary information to orders maintained by the reconstruction and matching libraries?

**Comment by sirinath** [comment]
Not orders but MM quotes. Also there is exchange specific meta data also.

**Comment by jvirtanen** [comment]
Well, at least in [NASDAQ TotalView-ITCH 5.0](http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHspecification.pdf) the market participant identifier, if known, is sent in the Add Order with MPID Attribution message. 

Do you have a particular trading venue in mind?

**Comment by sirinath** [comment]
I want to keep things as generic as possible. Started work on developing the trading engine.

**Comment by penberg** [comment]
IIRC, MPID is usually left blank these days. No harm in exposing it if it does exist, of course.

**Comment by jvirtanen** [comment]
See #57. MPIDs fall under the definition of auxliary order information.
